### ISSUE TITLE
Periodic raw status of resources in manifest work

### ISSUE THREAD

**Issue by maleck13** [open-cluster-management-io/enhancements#90]
I am new to this project, but I am investigating integrating a controller into the hub to manage N-S gateways in the spoke clusters and configure DNS etc based on the LBs used by those gateways. So my controller pays particular attention to the status of the gateway resource.

I am able to sync a gateway via a manifestwork, but when looking at how to get the status back I cam across this enhancement https://github.com/open-cluster-management-io/enhancements/tree/8fa2df88e1a046ac3855f10d8b9703002853332d/enhancements/sig-architecture/29-manifestwork-status-feedback#return-raw-status-data-of-the-applied-resource 

This works but is a little cumbersome. I noticed that returning the raw status was ruled out as it may result in too many updates to the hub? Would a more controlled periodic approach rather than on every update help solve this?

**Comment by qiujian16** [comment]
this has been implemented
/close
